# image will be published to ghcr.io/<user>/<name>
name: rhizome-blue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - md.obsidian.Obsidian
        - org.libreoffice.LibreOffice
        - org.onlyoffice.desktopeditors
        - io.github.zen_browser.zen
        - com.brave.Browser
        - com.protonvpn.www
        - org.inkscape.Inkscape
        - org.videolan.VLC
        - org.zotero.Zotero
        - io.github.peazip.PeaZip
        - me.proton.Pass
        
      remove:
        - org.gnome.eog
        - org.mozilla.Thunderbird
        - org.mozilla.firefox
        - org.kde.kcalc
        - org.kde.gwenview
        - org.kde.kontact
        - org.kde.okular
        - org.kde.kweather
        - org.kde.kclock
        - org.fkoehler.KTailctl
        - org.kde.haruna
        - org.fedoraproject.MediaWriter
        - io.missioncenter.MissionCenter
        - org.gnome.DejaDup
        
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

